### ISSUE TITLE
styled components support

### ISSUE THREAD

**Issue by timoly** [oayres/react-ssr#2]
Hi,
It would be nice to have support for styled components with ssr. Styled components support requires that getStyleTags api method is called after renderToString  and then the output is appended to the html template. https://www.styled-components.com/docs/advanced#server-side-rendering
This isn't possible currently because when looking at https://github.com/oayres/react-ssr/blob/0ea9144cf81eb766b937872601e06edd41b32f53/src/serverRender.js#L113 it seems that there's no way to add any custom logic to this step.

**Comment by oayres** [comment]
Hi timoly,

Thanks for this — good suggestion. I think there's a requirement to make this a little cleaner for consumers, but I think this is technically possible right now by doing the following: -

```
import { ServerStyleSheet, StyleSheetManager } from 'styled-components'
import customTemplate from './customTemplate'
import ssr from 'react-ssr'

const sheet = new ServerStyleSheet();
const Providers = ({children}) => (
  <StyleSheetManager sheet={sheet.instance}>
    {children}
  </StyleSheetManager>
)

const serverRender = ssr({
  Html: customTemplate(sheet)
})
```

Your customTemplate could look like...
```
const customTemplate = (sheet) => (
  class Html extends Component {
    // clone from react-ssr for now and extend with...
    render () {
      const styleTags = sheet.getStyleTags() // or sheet.getStyleElement();

      return (
        <html>
          <stuff />
          {styleTags}
        </html>
      )
    }
  }
}
```

I realise the docs / read me are super vague around this now and will try and revisit the overall structure for how this stuff is shown so it's a bit easier to follow and see how the options work. If you happen to try this or have any further questions, give me a shout.

Cheers
Owen

**Comment by timoly** [comment]
Thanks for the detailed help, this solution works great for my needs.
